#
# spring
#
spring:
  application:
    name: newex-dax-perpetual-scheduler
  mvc:
    favicon:
      enabled: false
  http:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  messages:
    basename: messages/messages
    always-use-message-format: true
    cache-seconds: 3600
    fallback-to-system-locale: false
  redis:
    host: 192.168.1.225
    port: 16379
    timeout: 60000
    password: xxx
    pool:
      max-active: 10
      max-idle: 5
      max-wait: -1
      min-idle: 2
#
# logging
#
logging:
  config: classpath:conf/logging/logback-spring.xml
  path: /home/admin/logs/newex/newex-perpetual-scheduler
  level:
    default: INFO
    commons: INFO
    dax: INFO
    mybatis: INFO

#
# actuator
#
management:
  security:
    enabled: false
  add-application-context-header: false
#
# newex
#
newex:
  app:
    name: newex-dax-perpetual-scheduler
    version: 1.0
    domain: coinmex.com
    supported-locales: 'en|en-US|zh-CN|zh-TW|zh-HK'
  perpetual:
    datasource:
      biz:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.223:3306/perpetual?allowMultiQueries=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&amp;rewriteBatchedStatements=true
        username: ppl_user
        password: xxx
        max-active: 10
        min-idle: 0
    config:
      online: 0
      module: 4
      dk-currency: cmdk
      system-bill-phones:
  feignClient:
    dax:
      users: newex-dax-users
      integration: newex-dax-integration
      extra: newex-dax-extra
      asset: newex-dax-asset
      market: newex-dax-market
xxl:
  job:
    accessToken: newex_!*0127aim
    admin:
      addresses: http://coinmex-scheduler-admin-0.coinmex-scheduler-admin:7001/
    executor:
      appname: xxl-job-executor-perpetual
      ip:
      port: 7001
      logpath: target/logs/jobhandler
      logretentiondays: 1

