#
# server
#
server:
  port: @server.port@
  error:
    whitelabel:
      enabled: false
  tomcat:
    max-threads: 2000
    accept-count: 4000
    max-connections: 20000
    min-spare-threads: 5
  connection-timeout: 2000
#
#  datasource
#
newex:
  portal:
     urls:
       seoStaticUrl: @newex.portal.urls.seoStaticUrl@
       accountStaticUrl: @newex.portal.urls.accountStaticUrl@
       spotStaticUrl: @newex.portal.urls.spotStaticUrl@
     x-frame-options:
       allowed-origins:
         - @newex.portal.xframeOptions.googleTagManager@
         - @newex.portal.xframeOptions.growingIO@
  app:
    name: @newex.app.name@
    version: @newex.app.version@
    domain: @newex.app.domain@
    supported-locales: 'en|en-US|zh-CN|zh-TW|zh-HK'
    env:
      name: @newex.app.env.name@
  security:
    csrf:
      referer-pattern: @newex.security.csrf.refererPattern@
    xss:
      url-patterns: @newex.security.xss.urlPatterns@
#
# spring
#
spring:
  mvc:
    favicon:
      enabled: false
  messages:
    basename: messages/messages
    always-use-message-format: true
    cache-seconds: 3600
    fallback-to-system-locale: false
  thymeleaf:
    mode: HTML
    cache: @spring.thymeleaf.cache.enabled@
#
#
# logging config file location
#
logging:
  config: @logging.config@
  path: @logging.path@
  level:
    default: @logging.level.default@
    commons: @logging.level.commons@
    dax: @logging.level.dax@
#
# actuator
#
management:
  security:
    enabled: false
  add-application-context-header: false
  port: 7002