#
# server
#
server:
  port: 7001
  error:
    whitelabel:
      enabled: false
  tomcat:
    max-threads: 3000
    accept-count: 6000
    max-connections: 20000
    min-spare-threads: 50
  connection-timeout: 2000
#
#  datasource
#
newex:
  market:
    datasource:
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.223:3306/market?characterEncoding=UTF-8&amp;autoReconnect=true&amp;rewriteBatchedStatements=true
        username: ppl_user
        password: xxx
        max-active: 100
        min-idle: 10
    data-key: newex_spider
    intra-prefix: admin
    intra-version: v1
  app:
    name: newex-dax-market
    version: 2.0
    domain: coinmex.com
    supported-locales: 'en|en-US|zh-CN|zh-TW|zh-HK'
    env:
      name: dev
  security:
    csrf:
      referer-pattern: all
    xss:
      url-patterns: /v1/*
#
# spring
#
spring:
  mvc:
    favicon:
      enabled: false
  messages:
    basename: messages/messages
    always-use-message-format: true
    cache-seconds: 3600
    fallback-to-system-locale: false
  redis:
    host: 192.168.1.225
    port: 16379
    timeout: 60000
    password: xxx
    pool:
      max-active: 500
      max-idle: 200
      max-wait: 2000
      min-idle: 2
#
# logging config file location
#
logging:
  config: classpath:conf/logging/logback-spring.xml
  path: /home/admin/logs/newex/newex-market
  level:
    default: WARN
    commons: INFO
    dax: INFO
    mybatis: INFO
#
# actuator
#
management:
  security:
    enabled: false
  add-application-context-header: false
  port: 7002
