#
# server
#
server:
  port: @server.port@
#
# spring
#
spring:
  cloud:
    config:
      server:
        git:
          uri: @spring.cloud.config.server.git.uri@
          search-paths: '{application}'
          strict-host-key-checking: false
          username: @spring.cloud.config.server.git.username@
          password: @spring.cloud.config.server.git.password@
          basedir: @spring.cloud.config.server.git.basedir@
          clone-on-start: true
          force-pull: true
          timeout: 60
        encrypt:
          enabled: false
  application:
    name: @newex.app.name@
#
# eureka
#
eureka:
  client:
    service-url:
      defaultZone: @spring.cloud.eureka.serviceUrl@
  instance:
    prefer-ip-address: true
    appname: @newex.app.name@
#
# management
#
management:
  security:
    enabled: false
#
# security
#
security:
  basic:
    enabled: false
  user:
    name: admin
    password: newex,0987
#
# security
#
#security:
#  user:
#    name: @security.user.name@
#    password: @security.user.password@
#
# logging config file location
#
logging:
  config: @logging.config@
  path: @logging.path@
  level:
    default: @logging.level.default@
    springcloud: @logging.level.springcloud@
#
# newex app
#
newex:
    app:
      name: @newex.app.name@
      version: @newex.app.version@
      domain: @newex.app.domain@
      env:
        name: @newex.app.env.name@
