server:
  port: @server.port@

#  数据库配置
spring:
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      username: @xxl.job.db.username@
      password: @xxl.job.db.password@
      url: @xxl.job.db.url@
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        connection-test-query: 'SELECT 1'
  freemarker:
    request-context-attribute: request  #req访问request
    suffix: .ftl  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/template/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
        number_format: '0.##'   #数字格式化，无小数点
newex:
  app:
    name: @newex.app.name@
    version: @newex.app.version@
    domain: @newex.app.domain@
    supported-locales: 'en|en-US|zh-CN|zh-TW|zh-HK'
    env:
      name: @newex.app.env.name@
  common:
    evn: prod
    ip: 10.100.0.50
    adminEmail: wx0126@126.com
    adminPhone: 13252736126

  feignClient:
    dax:
      integration: @newex.feignClient.dax.integration@
#
# mybatis
#
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
#
# xxl
#
xxl:
  job:
    accessToken: @xxl.job.accessToken@
    mail:
      host:
      port:
      username:
      password:
      sendNick:
    login:
      username:
      password:
    i18n:

logging:
  config: @logging.config@
  path: @logging.path@
  level:
    default: @logging.level.default@
    commons: @logging.level.commons@
    exchange: @logging.level.exchange@
    mybatis: @logging.level.mybatis@

