#
# server
#
server:
  port: 7001
  error:
    whitelabel:
      enabled: false
  tomcat:
    max-threads: 2000
    accept-count: 2000
    max-connections: 4000
    min-spare-threads: 5
  connection-timeout: 5000
#
#  datasource
#
newex:
  app:
    name: newex-dax-perpetual-openapi
    version: 2.0
    domain: newex.cc
    supported-locales: 'en|en-US|zh-CN|zh-TW|zh-HK'
    env:
      name: test
  perpetual:
    datasource:
      biz:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.223:3306/perpetual?allowMultiQueries=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&amp;rewriteBatchedStatements=true
        username: ppl_user
        password: xxx
        max-active: 10
        min-idle: 0
    config:
      online: 0
      module: 2
      dk-currency: cmdk
      robot: 21899634
      marketId: 10120827
  security:
    csrf.enabled: false
    xss.enabled: false
    exception-advice: false
    jwt.exception-advice: false
  web:
    support.exception-advice: false
  feignClient:
    dax:
      asset: newex-dax-asset
      users: newex-dax-users
      integration: newex-dax-integration
      market: newex-dax-market
  openapi:
    interceptor:
      auth:
        exclude-url-patterns: /api/v1/perpetual/public/**
    apikey:
      prefix: 'cmx-'
    rate-limiter:
      api-key-rate-limiter:
        max-request-times: 50
        seconds: 2
#
# spring
#
spring:
  mvc:
    favicon:
      enabled: false
  messages:
    basename: messages/messages
    always-use-message-format: true
    cache-seconds: 3600
    fallback-to-system-locale: false
  aop:
    proxy-target-class: true
  redis:
    host: 192.168.1.225
    port: 16379
    timeout: 60000
    password: xxx
    pool:
      max-active: 1000
      max-idle: 500
      max-wait: 2000
      min-idle: 2
#
# logging config file location
#
logging:
  config: classpath:conf/logging/logback-spring.xml
  path: /home/admin/logs/newex/newex-perpetual-openapi
  level:
    default: INFO
    commons: INFO
    dax: INFO
    mybatis: INFO
#
# actuator
#
management:
  security:
    enabled: false
  add-application-context-header: false
