#
# logging config file location
#
logging:
  config: @logging.config@
  path: @logging.path@
  level:
    default: @logging.level.default@
    springcloud: @logging.level.springcloud@
#
# management
#
management:
  security:
    enabled: false
#
# security
#
security:
  basic:
    enabled: false
  user:
    name: admin
    password: newex,0987
#
# eureka
#
---
spring:
  application:
    name: @newex.app.name@
  profiles: standalone
server:
  port: @eureka.server.port1@
eureka:
  instance:
    hostname: @eureka.server.host1@
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    renewal-percent-threshold: @eureka.server.renew-threshold@
    enable-self-preservation: false

---
spring:
  application:
    name: @newex.app.name@
  profiles: server1
server:
  port: @eureka.server.port1@
eureka:
  instance:
    hostname: @eureka.server.host1@
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://@eureka.server.host2@:@eureka.server.port2@/eureka/,http://@eureka.server.host3@:@eureka.server.port3@/eureka/
  server:
    renewal-percent-threshold: @eureka.server.renew-threshold@

---
spring:
  application:
    name: @newex.app.name@
  profiles: server2
server:
  port: @eureka.server.port2@
eureka:
  instance:
    hostname: @eureka.server.host2@
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://@eureka.server.host1@:@eureka.server.port1@/eureka/,http://@eureka.server.host3@:@eureka.server.port3@/eureka/
  server:
    renewal-percent-threshold: @eureka.server.renew-threshold@

---
spring:
  application:
    name: @newex.app.name@
  profiles: server3
server:
  port: @eureka.server.port3@
eureka:
  instance:
    hostname: @eureka.server.host3@
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://@eureka.server.host1@:@eureka.server.port1@/eureka/,http://@eureka.server.host2@:@eureka.server.port2@/eureka/
  server:
    renewal-percent-threshold: @eureka.server.renew-threshold@
#
# newex app
#
newex:
    app:
      name: @newex.app.name@
      version: @newex.app.version@
      domain: @newex.app.domain@
      env:
        name: @newex.app.env.name@
