#
#  数据库配置
#
newex:
  app:
    name: @newex.app.name@
    version: @newex.app.version@
    domain: @newex.app.domain@
    supported-locales: 'en|en-US|zh-CN|zh-TW|zh-HK'
    env:
      name: @newex.app.env.name@
  futures:
    datasource:
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: @newex.futures.main.datasource.url@
        username: @newex.futures.main.datasource.username@
        password: @newex.futures.main.datasource.password@
        max-active: 10
        min-idle: 0
    config:
        signName: @newex.futures.config.signName@
        phone: @newex.futures.config.phone@
  feignClient:
     dax.integration: @newex.feignClient.dax.integration@
  common:
    evn: prod
    adminEmail: wx0126@126.com

#
# spring
#
spring:
  mvc:
    favicon:
      enabled: false
  messages:
    basename: messages/messages
    always-use-message-format: true
    cache-seconds: 3600
  redis:
    host: @spring.redis.host@
    port: @spring.redis.port@
    timeout: @spring.redis.timeout@
    test-on-borrow: @spring.redis.testOnBorrow@
    password: @spring.redis.password@
    pool:
       max-active: @spring.redis.pool.max-active@
       max-idle: @spring.redis.pool.max-idle@
       max-wait: @spring.redis.pool.max-wait@
       min-idle: @spring.redis.pool.min-idle@

#
# logging config file location
#
logging:
  config: @logging.config@
  path: @logging.path@
  level:
    default: @logging.level.default@
    commons: @logging.level.commons@
    dax: @logging.level.dax@
    mybatis: @logging.level.mybatis@

xxl:
  job:
    accessToken: @xxl.job.accessToken@
    admin:
      addresses: @xxl.job.admin.addresses@
    executor:
      appname: @xxl.job.executor.appname@
      ip: @xxl.job.executor.ip@
      port: @xxl.job.executor.port@
      logpath: @xxl.job.executor.logpath@
      logretentiondays: @xxl.job.executor.logretentiondays@
#
# actuator
#
management:
  security:
    enabled: false
  add-application-context-header: false

